'use client'
// import './globals.css'
import Navbar from "./components/Navbar.jsx"
import { Inter } from "next/font/google";
import { AuthContextProvider } from './Context/AuthContext.jsx'
import "./globals.css"

const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  );
}
